export const SQUARE_CHECKOUT_STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
  FAILED: "FAILED",
} as const;

export const DIALOG_CLOSE_ANIMATION_MS = 200;
